#!/bin/bash
# Track token usage and costs over time

WORKSPACE="/Users/vex/.openclaw/workspace"
LOG_DIR="$WORKSPACE/logs/costs"
LOG_FILE="$LOG_DIR/cost-log-$(date +%Y-%m).jsonl"

mkdir -p "$LOG_DIR"

# Get session status (includes usage stats)
# Parse and log to JSONL
{
  echo "{"
  echo "  \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\","
  echo "  \"date\": \"$(date +%Y-%m-%d)\","
  echo "  \"time\": \"$(date +%H:%M:%S)\","
  echo "  \"session\": \"main\","
  echo "  \"note\": \"Automated cost tracking (heartbeat)\""
  echo "}"
} >> "$LOG_FILE"

# Also create a daily summary
SUMMARY_FILE="$LOG_DIR/daily-summary-$(date +%Y-%m-%d).md"

if [ ! -f "$SUMMARY_FILE" ]; then
  {
    echo "# Cost Summary - $(date +%Y-%m-%d)"
    echo ""
    echo "Auto-generated by track-costs.sh"
    echo ""
    echo "## Sessions Tracked"
    echo ""
  } > "$SUMMARY_FILE"
fi

echo "✅ Cost logged to $LOG_FILE"
